### ISSUE TITLE
random.nextLong(bound: Long) also returns negative values

### ISSUE THREAD

**Issue by axelfontaine** [serpro69/kotlin-faker#210] opened 2024-01-30 17:53 UTC
Even though the contract in the docs says the returned values will always be positive.

**Comment by serpro69** [comment] 2024-01-30 17:55
Will take a look at this. Thanks :)

**Comment by serpro69** [comment] 2024-02-01 08:03
I couldn't reproduce this.
I've also updated the test (https://github.com/serpro69/kotlin-faker/commit/a5510aceb2d254a1fbbb6b73155edb9deca6fc59) to generate more numbers with `nextLong(bound)` and make sure it asserts on `0 until bound`, and the test still passes.
Can you give me a minimal reproducible example for this issue so I can test it on my end.
Thanks.

**Comment by serpro69** [comment] 2024-03-30 16:11
It's been awhile since this issue has been opened w/o action, so I'm going to close it for now.
Feel free to re-open if you can provide more details on how to reproduce this @axelfontaine .
Thanks

**Closed by serpro69** 2024-03-30 16:11 UTC
Labels: bug :lady_beetle:, needs info :question:, core :zero::one:
