### ISSUE TITLE
Getting 'ClassCastException' when using kotlin-faker with Generics Type

### ISSUE THREAD

**Issue by mandanai** [serpro69/kotlin-faker#191] opened 2023-06-14 07:57 UTC
I use Kotlin-Faker to generate data with generics type like below.

```
data class BaseResponse<T>(
    val code: ResponseCode = ResponseCode.OK,
    val message: String = "",
    val error: String = "",
    val timestamp: ZonedDateTime = ZonedDateTime.now(),
    val data: T? = null,
    val status: String = ""
)

data class Car(
    val type: String = "",
    val color: String = "",
    val availableDate: ZonedDateTime = ZonedDateTime.now()
)

object CarMock {

    fun carSuccess(faker: Faker): BaseResponse<Car> {
        return faker.randomProvider.randomClassInstance {
            typeGenerator<ZonedDateTime> {
                ZonedDateTime.now()
            }

            namedParameterGenerator("code") {
                ResponseCode.OK
            }

            namedParameterGenerator("data") {
                faker.randomProvider.randomClassInstance<Car> { // <-- I think error from this
                    typeGenerator<ZonedDateTime> {
                        ZonedDateTime.now()
                    }
                }
            }
        }
    }
}
```

When run like

```
val faker = Faker()
val resultDetail = carSuccess(faker)
```

Then error like below

```
class kotlin.reflect.jvm.internal.KTypeParameterImpl cannot be cast to class kotlin.reflect.KClass (kotlin.reflect.jvm.internal.KTypeParameterImpl and kotlin.reflect.KClass are in unnamed module of loader 'app')
java.lang.ClassCastException: class kotlin.reflect.jvm.internal.KTypeParameterImpl cannot be cast to class kotlin.reflect.KClass (kotlin.reflect.jvm.internal.KTypeParameterImpl and kotlin.reflect.KClass are in unnamed module of loader 'app')
    at io.github.serpro69.kfaker.provider.misc.RandomClassProvider.randomClassInstance(RandomClassProvider.kt:142)
```

**Comment by serpro69** [comment] 2023-06-14 11:45
Hi @mandanai , thanks for opening the issue.
Yeah, I don't think I've ever tested generics with randomClassInstance generation. 
I will try to reproduce this and will look into how this can be fixed (I'm not sure if I have much time this month, but I will have some free time in July for sure). Unless you'd like to contribute a fix yourself?

**Comment by mandanai** [comment] 2023-06-14 16:26
Of course, I would like to contribute to this revision. I will try to fix this part.

**Comment by serpro69** [comment] 2023-06-15 06:39
> Of course, I would like to contribute to this revision. I will try to fix this part.

Great! Let me know if you need any help then.

**Comment by mandanai** [comment] 2023-07-06 09:31
@serpro69 At `RandomClassProvider.kt` from this `it.type.classifier`, I got T (KTypeParemeterImpl). How do I know the class type from the generic type, Do you have any ideas?

And for this line cast as `KClass<*>`, an exception event will occur.

<img width="538" alt="image" src="https://github.com/serpro69/kotlin-faker/assets/3318865/cdf7a597-bdc2-4ba4-a785-75c7b51ebd1b">

**Comment by serpro69** [comment] 2023-07-10 19:23
Hi @mandanai ,

I do not think it's possible to get the class type from generic type; you have no type information for T because JVM erases the type information. Though kotlin might have some tricks up it's sleeve that could help solve this. What first comes to mind is [reified type parameters](https://kotlinlang.org/docs/inline-functions.html#reified-type-parameters), but that of course only works with inline functions (at least for now)

I'm on vacation currently, with limited access to internet. But I'll try to search around once I'm back if you don't find an answer to this yourself by then.
I do suspect it might not be possible to fix this with current limitations of generic types.

**Comment by mandanai** [comment] 2023-07-12 06:18
Hi @serpro69 
Many thanks, I tried to find many ways but still haven't found the solution to this problem and if applied I can not use `randomClassInstance` directly with that Class; I use a separate `randcomClassInstance` and assign values ​​to a generic type instead.

**Comment by serpro69** [comment] 2023-07-12 21:21
> I use a separate `randcomClassInstance` and assign values ​​to a generic type instead.

Does this mean you have a "workaround" for this issue, @mandanai ?
If so, we should at least document how to work around this issue until generic properties in classes are properly supported with `randomClassInstance`

**Comment by mandanai** [comment] 2023-08-11 06:32
Hi @serpro69 
Right, I have a workaround for this issue
Example in below; it's work for me:

```
data class BaseResponse<T>(
    val code: ResponseCode = ResponseCode.OK,
    val message: String = "",
    val error: String = "",
    val timestamp: ZonedDateTime = ZonedDateTime.now(),
    val data: T? = null,
    val status: String = ""
)

data class Car(
    val type: String = "",
    val color: String = "",
    val availableDate: ZonedDateTime = ZonedDateTime.now()
)

object CarMock {

    fun carSuccess(faker: Faker): BaseResponse<Car> {
        return BaseResponse(
            code = ResponseCode.OK,
            message = faker.lorem.punctuation(),
            status = "SUCCESS",
            data = getCar(faker)
        )
    }

   private fun getCar(faker: Faker): Car {
        return faker.randomProvider.randomClassInstance {
            typeGenerator<ZonedDateTime> {
                ZonedDateTime.now()
            }
        }
    }
}
```

**Comment by serpro69** [comment] 2023-08-30 09:02
Yeah, I would do something similar myself :) I guess it's currently the only way to go about it due to how JVM deals with generics. I'm adding this to docs and closing the issue for now, but feel free to re-open if you find out how this can be solved in a better fashion.
Thanks!

**Closed by serpro69** 2023-08-30 09:02 UTC
Labels: bug :lady_beetle:, core :zero::one:
