### ISSUE TITLE
Problems with Fasterxml 2.10.0 and Springboot 2.2.1

### ISSUE THREAD

**Issue by ksinkar** [serpro69/kotlin-faker#20] opened 2019-12-15 21:27 UTC
I cannot use Faker with my latest Springboot project (2.2.1.RELEASE)

``` shell
java.lang.NoSuchMethodError: com.fasterxml.jackson.module.kotlin.KotlinModule.<init>(IZZZILkotlin/jvm/internal/DefaultConstructorMarker;)V

	at io.github.serpro69.kfaker.Mapper.<clinit>(Mapper.kt:12)
	at io.github.serpro69.kfaker.FakerService.readCategory(FakerService.kt:121)
	at io.github.serpro69.kfaker.FakerService.load(FakerService.kt:65)
	at io.github.serpro69.kfaker.FakerService.<init>(FakerService.kt:30)
	at io.github.serpro69.kfaker.Faker.<init>(Faker.kt:13)
	at io.github.serpro69.kfaker.Faker.<init>(Faker.kt:12)
```

I fixed it by upgrading fasterxml to 2.10.1.

**Comment by serpro69** [comment] 2020-01-28 06:15
This could be caused by differences in 2.10.0 and 2.10.1

I've had the "need to fix dependencies" thought in the back of my head for awhile now (probably using the shadow plugin), but didn't have time as of late to add this. Feel free to submit a PR if you want.

For now upgrading your dependency seems like the best workaround. Else you can also try to exclude `jackson-module-kotlin` from `faker`'s dependencies.

**Comment by rpmoore** [comment] 2020-04-29 22:43
I'm also encountering the same issue but with Jackson 2.11. Exact same stack trace.

**Comment by serpro69** [comment] 2020-04-30 08:02
What spring version are you using @rpmoore ? Will try to reproduce it.

**Comment by rpmoore** [comment] 2020-04-30 14:45
We're not using spring. I also tried down reving Jackson to 2.10.1 and that didn't resolve the issue. I can play with some of the other dependencies to see what it is.

**Comment by rpmoore** [comment] 2020-05-01 18:08
Doing a little digging I found this issue https://github.com/FasterXML/jackson-module-kotlin/issues/279

Seems like if you update to 2.10.2 that should resolve some of the issues going forward.

**Comment by serpro69** [comment] 2020-05-01 18:12
Thanks for digging that up @rpmoore Will update all of the dependencies and push the change on the weekend. Hopefully that will help. 
I've also tried shading the dependencies, but there's no documentation on using gradle shade plugin with kotlin-dsl syntax, so that's still in progress.

**Comment by serpro69** [comment] 2020-05-01 18:40
@rpmoore please check if faker version `1.1.2` fixes it. I've bumped jackson dependencies to 2.11.0

**Comment by rpmoore** [comment] 2020-05-04 14:08
I'll give it a try today and let you know.

**Comment by rpmoore** [comment] 2020-05-06 20:27
That seemed to do the trick for me! I can run my tests without issue now.

**Comment by serpro69** [comment] 2020-05-07 05:46
Great, thanks for confirming @rpmoore 
Closing this for now. @ksinkar feel free to reopen if this is not fixed for you.

**Closed by serpro69** 2020-05-07 05:46 UTC

**Comment by rpmoore** [comment] 2020-05-08 16:58
Yeah, it's working like a champ now. This has been super helpful!

**Comment by dimw** [comment] 2025-02-28 20:29
Using kotlin-faker v2.0.0-rc.9 with Spring Boot 3.4.1 and Spring Data, and getting the following error:
```
Caused by: java.util.ServiceConfigurationError: com.fasterxml.jackson.databind.Module: Provider com.fasterxml.jackson.module.kotlin.KotlinModule not found
```

Adding the following dependency seems to resolve the issue:
```kotlin
implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.18.2")
```

**Comment by serpro69** [comment] 2025-02-28 21:18
Could you open a separate issue for this, @dimw? With a minimal reproducible example, if possible 🙏 
Thanks!
