### ISSUE TITLE
Reflect issue in minified android apk. Add proguard section in README?

### ISSUE THREAD

**Issue by qavan** [serpro69/kotlin-faker#106] opened 2021-11-12 08:42 UTC
Nice lib, thx!

I received ```kotlin.jvm.KotlinReflectionNotSupportedError: Kotlin reflection implementation is not found at runtime. Make sure you have kotlin-reflect.jar``` error at runtime in minified android build but all my modules includes **_reflect_** dependency...

Got correct stacktrace only after cleaning **ALL** caches (in project, in ```.gradle``` transform and build-caches dirs).

Correct stacktrace which helps me fix problem was ```Property 'unique' (JVM signature: getUnique()Lio/github/serpro69/kfaker/provider/GameOfThrones;) not resolved in class te1```
Adding ```-keepclasseswithmembers class io.github.serpro69.**{*;}``` in proguard rules and removing```android.enableR8.fullMode=true``` fixed problem.

Using non unique getters not receivies exception

**Comment by serpro69** [comment] 2021-11-12 09:19
Hi @qavan ,
Thanks for reporting this issue.

Just to understand, should we update documentation to reflect usage with android/proguard or do you think there's a need for a fix in the code?

Would you be willing to make a PR for the readme?

**Comment by qavan** [comment] 2021-12-13 15:11
Hmm, i think reason not in code.
I got same issue with faker `1.9.0`, so I think my rule is not correct. Or maybe is only R8 issue for newest kotlin versions(I use Kotlin `1.6.0` with `gradle 7.3` + `android gradle plugin 7.0.4`). According this I can't make 100% helpful pull request, maybe later.

**Comment by serpro69** [comment] 2021-12-13 16:04
`kotlin-faker:1.9.0` uses kotlin `1.6.0` as well - #108 - so if you've tried this version of faker and have the same issue as before, then I doubt it's because of kotlin version discrepancy.

Could you make a sample minimal project to reproduce this issue?

**Comment by andrea157** [comment] 2021-12-22 10:19
Hi, I have a similar problem with obfuscation from 1.6.0, at this [link](https://github.com/andrea157/MyAppTest) I provided an example project showing the error

**Comment by serpro69** [comment] 2021-12-28 08:43
Thanks @andrea157 .

I don't think it's an issue with kotlin-faker, especially seeing that your example does not use kotlin-faker at all.
I think the existing proguard rules that are embedded in kotlin-reflect.jar are broken with release 1.6.0+
But I'll play around with this when I have time and see if I can at least add some info to the docs for a workaround. Otherwise feel free to submit a PR for the same.

**Comment by serpro69** [comment] 2024-03-30 16:32
Hi @qavan ,
This issue has been w/o action for some time now, so I'm going to close it.
Are you still facing problems with proguard in latest kotlin-faker and kotlin versions? If so - feel free to re-open the issue.
Thanks

**Closed by serpro69** 2024-03-30 16:32 UTC
Labels: docs :page_with_curl:
